### PR TITLE
Completes issue 53

### PR DESCRIPTION
**Pull request by amruta-jv**

### CODE REVIEW

**Comment by amruta-jv** [comment]
@burtbeckwith Could you please look into this PR ASAP.

**Comment by burtbeckwith** [comment]
I'm not a plugin author, just a contributor.

**Comment by amruta-jv** [comment]
@j4y @lucastex Please look into this PR.

**Comment by lucastex** [comment]
Hi @amruta-jv , @sronderos and @j4y are the head developers :)

**Comment by bostanio** [comment]
According to Jenkins this PR doesn't even compile. Also it doesn't follow existing patterns. Please fix and we can look again.

**Comment by amruta-jv** [comment]
@bostanio I want to get bucket list for a given credentials(accessKey and secretKey) so there is a need for new method right?

**Comment by bostanio** [comment]
@amruta-jv yes a new method is fine but your method doesn't follow the pattern that other do in terms of getting credentials. It also doesn't seem to compile. See my specific comments on the diff for what needs to be fixed.

**Comment by amruta-jv** [comment]
@bostanio  Now can you please check this.

**Comment by bostanio** [comment]
Looks like this compiles but it doesn't address the comments around the other issues. Specifically that we don't need a new overload of the buildJetS3tCredentials method.

**Comment by amruta-jv** [comment]
@bostanio I want bucket list for a given credential so overload is a must, isn't it?

**Comment by bostanio** [comment]
I guess I'm confused as to why you want a different credential than the one configured for use by the plugin?

**Comment by j4y** [comment]
Another issue with this PR is that the listBuckets API returns a list of buckets that were created within a given AWS account.  It doesn't give you a list of buckets that you have access to.

**Pull request closed without merging**
