### PR TITLE
Grails 3 migration

### PR DESCRIPTION
**Pull request by ctoestreich**
I can also keep this in the grails-plugin-consortium group and make you a developer on this if you want me to manage the releases to bintray.

This conversion got the AWS stuff working but the email stuff and scripts need some love.

### CODE REVIEW

**Comment by ctoestreich** [comment]
@j4y Any update on taking in this PR and adding to grails bintray?

**Comment by j4y** [comment]
This PR as is cant merge because it will break the 2.3.x, 2.4.x, and 2.5.x versions.  Perhaps it could land into the grails-3.x branch?

**Comment by ctoestreich** [comment]
First branch current master into grails-2 then accept

**Comment by ctoestreich** [comment]
That way you can still work and publish grails 2 stuff on that branch.

**Comment by ctoestreich** [comment]
@j4y I am also happy to host this at the grails-plugin-consortium repo and add you as maintainer rights.  Then this can be left as grails 2 and the other can be grails 3.  Let me know.  I already have the code ready to add to the mainline grails bintray plugins.  I did this because we need this for a g3 project. :)

https://github.com/Grails-Plugin-Consortium/grails-aws

https://bintray.com/ctoestreich/grails-plugins/org.grails.plugins%3Agrails-aws/view

**Comment by j4y** [comment]
I merged this and uploaded it to bintray.  Please check and let me know if it's as you expect.

Thanks for your help.

https://bintray.com/grails-aws/grails-plugins/org.grails.plugins%3Agrails-aws/2.0.3/view

**Pull request merged**
